### ISSUE TITLE
pinyin data

### ISSUE THREAD

**Issue by lepture** [cn/GB2260#12]
Add pinyin name in txt files:

```
110000	北京市	běi-jīng-shì
```

**Comment by tonyseek** [comment]
It could be achieved by third libraries. (e.g. [pinyin](https://pypi.python.org/pypi/pinyin/0.2.5)). We may need to describe this way in documents instead of writting those libraries again.

**Comment by lepture** [comment]
放在各个语言里自己实现

**Comment by WestFarmer** [comment]
In GB2260 there is already pinyin data, why need to  implement  ?
![图片](https://github.com/cn/GB2260/assets/14016562/f84df154-ae75-42ff-9b77-3775793b2b9f)
