### ISSUE TITLE
加入 Ruby 实现

### ISSUE THREAD

**Issue by wolflee** [cn/GB2260#13]
https://github.com/wolflee/GB2260.rb

**Comment by lepture** [comment]
邀请你了

**Comment by lepture** [comment]
似乎已经实现了 spec v0.1

JS 也正在迁移：https://github.com/cn/GB2260.js

**Comment by wolflee** [comment]
:sweat: 在哪里看？另外，需要迁移至 cn/GB2260.rb 么？

**Comment by lepture** [comment]
@wolflee 可以迁移过来呀。

**Comment by wolflee** [comment]
好，周一弄

**Comment by wolflee** [comment]
@lepture 帮忙建一个 cn/GB2260.rb 的 repo 吧，我一会儿把代码迁移过来。

**Comment by lepture** [comment]
@wolflee 可以直接转移过来的。我刚给你加了 admin 权限了。

**Comment by wolflee** [comment]
Transfer 了，可能需要更新一下 metadata，这边先关掉了。
