### ISSUE TITLE
来源是否准确

### ISSUE THREAD

**Issue by timothyqiu** [cn/GB2260#17]
查询资料的过程中，发现作为推荐标准的 GB/T 2260，至少存在 GB/T 2260-2002 和 GB/T 2260-2007 两个版本，而且 GB/T 2260-2007 是直接代替 GB/T 2260-2002 的。

而 Repo 中从国家统计局网站抓取的数据，2002 至 2007 之间每一年都有新版本。这些数据显然不属于 GB/T 2260 的任何版本。

所以，似乎国家统计局网站上公布的行政区划代码实际上并不是 GB/T 2260 的代码。至少 2002 至 2007 年间的不是。

**Comment by tonyseek** [comment]
> 查询资料的过程中，发现作为推荐标准的 GB/T 2260，至少存在 GB/T 2260-2002 和 GB/T 2260-2007 两个版本，而且 GB/T 2260-2007 是直接代替 GB/T 2260-2002 的。

可否提供一下“查询资料的过程中”具体资料来源呢？数据是我和 @lepture 收集的，目前苦于没有找到比国家统计局网站更权威的来源。[维基百科词条](https://zh.wikipedia.org/zh/中华人民共和国行政区划代码)指向的同样是统计局的网址。

**Comment by timothyqiu** [comment]
从 [国家标准化管理委员会的国标查询页面](http://www.sac.gov.cn/SACSearch/outlinetemplet/gjbzcx.jsp) 查「GB/T 2260」可以看到现行的版本是 2007；2007 代替 2002；2002 代替 1999……

从 GB/T 2260-2007 的前言来看，标准文档的历史版本应该且只有这些版本：

* 1980
* 1982
* 1984
* 1986
* 1988
* 1991
* 1995
* 1999
* 2002
* 2007

「中华人民共和国行政区划代码」 和「GB/T 2260」应该是两回事。前者由统计局每隔一段时间整理发布；后者有标准文档对应，有严格的标准号和代替关系，看上去应该是基于前者的（标准文档除了行政区划数字代码，还有一套字母代码）。

根据政策免费公开的目前应该只有 GB 强制标准，GB/T 还没有。但是网上搜一下可以找到影印版 PDF。

介于这个 Repo 的名字叫 GB2260，可能标准文档更权威一些，而不是尚未标准化的国家统计局的数据……

**Comment by tonyseek** [comment]
嗯…… 这么看来似乎的确应该在命名空间上区分下两个数据源…… 比如统计局版数据放到 `gb2260.contrib` 里……

@lepture

**Comment by lepture** [comment]
我觉得不必要，只需要将 revision 区别开来就可以了。

**Comment by damonchen** [comment]
我以为当GB/T发布的时候，有些时候，有些地方仍旧是县，但是当某个地方撤县改市的时候，不可能让GB/T标准再发布一次，因此国家统计局的数据更具有现实的意义。

**Comment by damonchen** [comment]
这个是2003年发布的
http://www.stats.gov.cn/tjsj/tjbz/xzqhdm/200302/t20030219_38299.html  

这个是2008年发布的
http://www.stats.gov.cn/tjsj/tjbz/xzqhdm/200802/t20080215_38311.html

这个是2015年发布的
http://www.stats.gov.cn/tjsj/tjbz/xzqhdm/201504/t20150415_712722.html

查询南京下面的 高淳，就会发现 县 改 区，编码仍旧是 320125 ，但是GB/T是不可能因为这么小的事情而变更的。

**Comment by timothyqiu** [comment]
这个 issue 并不是说国家统计局的数据不准确，而是国家统计局的数据用在这里名不副实。

国家统计局的数据无疑是当下最精确的，但国家统计局的数据 ≠ GB/T 2260 的数据也是无疑的。而库的名字叫 GB 2260，实际上用的却不是 GB/T 2260 的数据，有挂羊头卖狗肉之嫌。

**Comment by lepture** [comment]
这个问题实际上和 w3c 标准与浏览器实现是一样的道理，GB2260 标准是在国家统计局的数据上确定的，它不可能因为一点点数据更新就重新发布一次标准。

国家统计局的数据在实际使用时更有意义，我们把其它 revisions 当作是方言，把国家标准化管理委员会的数据当作是普通话。

我在上面说过了：

> 我觉得不必要，只需要将 revision 区别开来就可以了

**Comment by timothyqiu** [comment]
了解了。我觉得至少只要能够在库中对标准与非标准数据有所区分即可 :)

**Comment by lepture** [comment]
@timothyqiu 做了一些调整：

https://github.com/cn/GB2260/pull/20

https://github.com/cn/GB2260/pull/21

这样既实用，又兼顾标准。
