### ISSUE TITLE
IRC / librelist / Gitter

### ISSUE THREAD

**Issue by lepture** [cn/GB2260#26]
需要一个沟通工具，issue 还是不太适合讨论。大家投票选一下吧：
1. IRC (freenode)
2. Mail list (librelist)
3. Gitter

另外还可以选 Slack 和 Bearychat，但是这两者不公开，不推荐使用。

**Comment by tonyseek** [comment]
个人推荐 librelist

因为项目主要参与者都不是全职做这件事，邮件在沟通上更能容忍非实时性。

**Comment by wolflee** [comment]
:+1::two:

**Comment by gaomd** [comment]
Slack 免费版没有聊天记录永久保存功能。
Gitter 个人不喜欢。

我认为项目自带的 issues 足够了。issues 与项目的结合更紧密，通过邮件通知、回复与 librelist 也没有本质区别。

**Comment by tonyseek** [comment]
@gaomd Issue 会在 GitHub Timeline 刷屏，如果我发言，关注了我而没关注这个项目的人也会被 spam

**Comment by gaomd** [comment]
@tonyseek 刷屏应该是 GitHub 或者第三方插件甚至是关注者自己去解决的事情，从这个理由来看，独立的讨论工具对项目并没有带来好处，反而会增加新来者的学习曲线（搜索 issues、在 commit 中使用 `Fix #3` 等操作变得困难）。

**Comment by tonyseek** [comment]
> 刷屏应该是 GitHub 或者第三方插件甚至是关注者自己去解决的事情

不觉得。就我个人而言我是始终不愿意 spam 关注者的，我不会去让他们每人装个插件、不喜欢就 unfollow 我，或者等 GitHub 解决了这个问题我再继续参与这个项目。

现在的问题在于，类似 GB2260 数据来源，或者 Spec，尚有许多未成定论，需要大量讨论甚至解决争执。而邮件/即时通信工具所能容忍的讨论密度是可以比 Issue 大很多的。邮箱提供商和客户端也很普遍地实现了过滤器一类的功能。而搜索归档这些，Google Groups / Librelist 一类的邮件列表服务一直都有。

除此以外，IRC/邮件列表本来就是很多开源项目和组织的标配，为什么就会增加新来者学习曲线呢？何况 IRC/邮件列表本来就是面向组织者、关心项目的参与者，而不是所有用户的。

**Comment by lepture** [comment]
Join Gitter: https://gitter.im/cn/GB2260
